config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from scrape.urls import router as scrape_router
# from scrape.urls import router_custom as scrape_router_custom

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('scrape/', include('scrape.urls')),
    # path('', include('display.urls')),
    path('api/', include(scrape_router.urls)),
    # path('api/search/', include(scrape_router_custom.urls)),

    # re_path('', TemplateView.as_view(template_name='index.html')),
]

display/urls.py
from django.urls import path
from display import views


app_name = 'display'

urlpatterns = [
    path('', views.index, name="index"),
    path('admin', views.admin, name="admin"),
    path('store_list', views.store_list, name="store_list"),
    path('show_details/<str:area_q>/<str:store_q>', views.show_details, name="show_details"),
]

display/models.py
from django.db import models

# Create your models here.

display/views.py
import json
from django.http import JsonResponse
from datetime import datetime
from scrape import models
# from scrape.scrape_tb import scrape_tb
from site_packages.my_module import Compare_storeName

from django.shortcuts import render, redirect
from django.db.models import Q

from pprint import pprint as pp
from devtools import debug


def admin(request):
    return redirect('/admin/')


def index(request):

    context = {}

    return render(request, "display/index.html", context)


def store_list(request):
    area_q: str = request.GET.get('area')
    store_q: str = request.GET.get('store')

    context = {
        "area": area_q,
        "store_q": store_q,
    }
    return render(request, "display/store_list.html", context)


# デバッグ用
# def scra(request):
#     scrape_tb("千葉県","船橋市")
#     return redirect('/')




def show_details(request, area_q, store_q):
    area_obj = models.Area.objects.get(area_name__icontains=area_q)

    store_objs_in_area = models.Store.objects.filter(area=area_obj)
    # 検索ーーーーーーー
    if store_q:
        match_store_obj_list = [s for s in store_objs_in_area if store_q in s.store_name]
        compare = Compare_storeName()
        store_kouho_dict = compare.search_store_name(store_q, store_objs_in_area, min_ratio=0.2)  # 一致率0.2以上を集める
        sorted_store_obj_list = sorted(store_kouho_dict.items(), key=lambda x: x[1]["ratio"], reverse=True)  # ratio順にソート
        sorted_store_obj_list = [o[0] for o in sorted_store_obj_list]  # objだけとる
        sorted_store_obj_list = match_store_obj_list + sorted_store_obj_list
        sorted_store_obj_list = sorted(set(sorted_store_obj_list), key=sorted_store_obj_list.index)  # 順番変わらないようにset
    else:
        sorted_store_obj_list = store_objs_in_area.order_by("store_name")

    media_type_objs = models.Media_type.objects.all()

    stores_data_list = []
    for store_obj in sorted_store_obj_list:
        store_dict = {"store_name": store_obj.store_name}
        store_dict["media_type"] = list(media_type_objs.values())

        rate_list = []
        review_count_list = []

        for i, media_type_obj in enumerate(media_type_objs):
            try:
                media_data_objs = models.Media_data.objects.filter(store=store_obj, media_type=media_type_obj)  # getで取りたいが、.values()が使えなくなる
                media_data = list(media_data_objs.values())[0]
            except Exception as e:
                # print(type(e), e, media_type_obj, 'media_data_objがありません。')
                store_dict["media_type"][i]["media_data"] = {}
            else:
                rate_list.append(media_data["rate"])
                review_count_list.append(media_data["review_count"])
                store_dict["media_type"][i]["media_data"] = media_data
                # 星用点数ーーー
                store_dict["media_type"][i]["media_data"]["rate_for_star"] = round(media_data["rate"],1)

                review_objs = models.Review.objects.filter(media=media_data_objs[0]).order_by('-review_date')
                store_dict["media_type"][i]["media_data"]["review"] = list(review_objs.values())
                # 星用点数ーーー
                for ii, review in enumerate(store_dict["media_type"][i]["media_data"]["review"]):
                    try:
                        store_dict["media_type"][i]["media_data"]["review"][ii]["review_point_for_star"] = round(review["review_point"], 1)
                    except TypeError: # noneがある
                        store_dict["media_type"][i]["media_data"]["review"][ii]["review_point_for_star"] = "0.0"

        registed_media_type = []
        for i in store_dict["media_type"]:
            try:
                if i["media_data"]:
                    registed_media_type.append(i["media_type"])
            except Exception:
                pass
        
        store_dict["registed_media_type"] = registed_media_type
        store_dict["only_uber_flg"] = True if registed_media_type == ["uber"] else False

        # 総合レートーーーーーーーー
        rate_list = [r for r in rate_list if r]  # 0, noneを除去
        try:
            store_dict["total_rate"] = round(sum(rate_list) / len(rate_list), 2)
            store_dict["total_rate_for_star"] = round(sum(rate_list) / len(rate_list), 1)

        except Exception:  # 0, noneを除去して無くなっちゃったものに対して。
            store_dict["total_rate"] = 0
            store_dict["total_rate_for_star"] = 0

        # 総合レビュー数ーーーーーーー
        review_count_list = [r for r in review_count_list if r]  # 0, noneを除去
        try:
            store_dict["total_review_count"] = sum(review_count_list)
        except Exception:  # 0, noneを除去して無くなっちゃったものに対して。
            store_dict["total_review_count"] = 0

        stores_data_list.append(store_dict)
    # debug(stores_data_list)
    return JsonResponse(stores_data_list, safe=False)

display/templates/display/details.html
{% extends 'display/index.html' %}
{% load static %}

{% block content %}


<div id="store_data">
    <p v-for="item in store_name">[[item]]</p>
</div>






{{ store_obj.store_name }}

<table>
    {% for media, review_objs in review_dict.items %}
        <tr>
            <th class="media">{{media}}</th>
        </tr>
        <tr>
            {% for obj in review_objs %}
                <td>
                    <p class="date">{{obj.review_date|date:"Y年m月"}}</p>
                </td>
            {% endfor %}
        </tr>
        <tr>
            {% for obj in review_objs %}
                <td>
                    <span class="rate_num">{{obj.review_point}}</span>
                    <span class="rate rate0" data-rate="{{obj.review_point|floatformat:1}}"></span>
                </td>
            {% endfor %}
        </tr>
        {% if media == "食べログ" %}
        <tr>
            {% for obj in review_objs %}
                <td>
                    <p class="title">{{obj.title| truncatechars:50 }}</p>
                </td>
            {% endfor %}
        </tr>
        {% endif %}
        <tr>
            {% for obj in review_objs %}
                <td>
                    <p class="content">{{obj.content | linebreaksbr | truncatechars:50 }}</p>
                </td>
            {% endfor %}
        </tr>

    {% endfor %}
</table>


<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>

var store_data = new Vue({
    delimiters: ["[[", "]]"],
    el: "#store_data",
    data: {
        store_name: [],
    },
    mounted: function () {
        axios.get('{% url "display:to_axios" store_q=store_obj.store_name %}')
            .then(function (response) {
                for(var d in response.data){
                    var item = response.data[d];
                    store_data.store_name.push(item.store_name)
                }
                {% comment %} store_data.store_name = response.data[0].store_name; {% endcomment %}
            });
    },
})

</script>


{% endblock content %}

display/templates/display/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>飲食店レビューまとめ</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/store_list.css' %}">



    <!-- datepicker使うための。だったけど、これがないとjsが動作しない -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <!-- --------------------- -->




</head>


    
    
<body>
{% block content %}
<form action="{% url 'display:store_list' %}" method='GET'>
    <input type="text" name="area">
    <input type="text" name="store">
    <input type="submit">
</form>

{% comment %} デバッグ用
<a href="{% url 'display:scra' %}">scra</a> {% endcomment %}
<div class="func-btn">
{% comment %} <a href="{% url 'display_part:index' %}" class="function-btn"><button>リセット</button></a>
<a href="{% url 'upload_part:index' %}" class="function-btn"><button>取り込み</button></a> {% endcomment %}
<a href="{% url 'display:admin' %}" class="function-btn"><button>管理画面</button></a>
</div>

<a href="{% url 'scrape:scrape_run' %}">scrape_run</a>





{% endblock content %}


</body>

display/templates/display/store_list.html
{% extends 'display/index.html' %}
{% load static %}

{% block content %}

<h1>{{area}}</h1>

<div id="store_items">
    <div v-for="store in stores_data_list" class="store_item" >
        <span @click="show_details(store)" class="store_btn" name="store_link" >[[store.store_name]]</span>

        <span v-show="store.only_uber_flg" class="uber_limited">UberEats限定</span>
        <span class="rate_num_total">[[store.total_rate]]</span>
        
        
        <span class="rate" :data-rate=[[store.total_rate_for_star]]></span>
        <span class="review_count tota_review_count">[[store.total_review_count]]</span>
        
        <div class="media_rate">
            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'google' && media_type.media_data.id">
                {% comment %} store.registed_media_type.includes('google') {% endcomment %}
                    <a :href=[[media_type.media_data.url]] target="_blank">Google</a>
                    <span class="google_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count google_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'tb' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">食べログ</a>
                    <span class="tb_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count tb_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'gn' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">ぐるなび</a>
                    <span class="gn_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count gn_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'hp' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">HotPepper</a>
                    <span class="hp_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count hp_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'retty' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">Retty</a>
                    <span class="retty_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count retty_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'uber' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">UberEats</a>
                    <span class="uber_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count uber_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'demaekan' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">出前館</a>
                    <span class="demaekan_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count demaekan_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>

            <span v-for="media_type in store.media_type">
                <span v-if="media_type.media_type === 'foodpanda' && media_type.media_data.id">
                    <a :href=[[media_type.media_data.url]] target="_blank">フードパンダ</a>
                    <span class="foodpanda_rate">[[media_type.media_data.rate]]</span>
                    <span class="rate" :data-rate=[[media_type.media_data.rate_for_star]]></span>
                    <span class="review_count foodpanda_review_count">[[media_type.media_data.review_count]]</span>
                </span>
            </span>
        </div>


        <div v-show="store.seen" class="detail">
            <div v-for="media_type in store.media_type">
                <div v-if="media_type.media_data.id">
                    <div class="media_name">
                        [[media_type.official_name]]
                    </div>
                    <div v-if="media_type.media_type === 'tb'">
                        <div v-for="review in media_type.media_data.review">
                            <p class="title"><b>[[review.title | top50]]</b></p>
                            <span class="review_point_num">[[review.review_point]]</span>
                            <span class="rate" :data-rate=[[review.review_point_for_star]]></span>
                            <span class="reivew_date">[[review.review_date | Ym]]</span>
                            <p class="review_content">[[review.content | top50]]</p>
                        </div>
                    </div>
                    <div v-else-if="media_type.media_type === 'hp'">
                        <div v-for="review in media_type.media_data.review">
                            <span class="reivew_date">[[review.review_date | Ym]]</span>
                            <p class="review_content">[[review.content | top50]]</p>
                        </div>
                    </div>
                    <div v-else>
                        <div v-for="review in media_type.media_data.review">
                            <span class="review_point_num">[[review.review_point]]</span>
                            <span class="rate" :data-rate=[[review.review_point_for_star]]></span>
                            <span class="reivew_date">[[review.review_date | Ym]]</span>
                            <p class="review_content">[[review.content | top50]]</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



                





<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>

var store_data = new Vue({
    delimiters: ["[[", "]]"],
    el: "#store_items",
    data: {
        stores_data_list: [],
    },
    methods:{
        show_details: function(store){
            var index_num = this.stores_data_list.indexOf(store);
            this.stores_data_list[index_num].seen = !this.stores_data_list[index_num].seen;
        },
    },
    created: function () {
        axios.get('{% url "display:show_details" area_q=area store_q=store_q %}')
            .then(function (response) {
                console.log(response.data);
                for(var d in response.data){
                    var item = response.data[d];
                    item.seen = false;

                    if(!item.total_rate){
                        item.total_rate = "-";
                        item.total_rate_for_star = "0.0";
                    };
                    for(var n in item.media_type){
                        try{
                            item.media_type[n].media_data.review = item.media_type[n].media_data.review.slice(0,3);
                        } catch{};
                    };
                    store_data.stores_data_list.push(item);
                };
            })
            .catch(function(error){
                console.log(error);
            })
            .finally(function(){
            })
    },
})


Vue.filter("top50", function(value){
    return value.slice(0,50);
})
Vue.filter("fix1", function(value){
    return Number(value).toFIxed(1);
})
Vue.filter("Ym", function(value){
    var date = new Date(value);
    var Ym = date.getFullYear() + "年" + ("0" + (date.getMonth()+1)).slice(-2) + "月";
    return Ym;
})


// console.log(store_data.stores_data_list)



</script>


{% endblock content %}